cache:
  replicaCount: 1
  limit:
    memory: "100Mi"
    cpu: "50m"
db:
  replicaCount: 1
  request:
    memory: "64Mi"
    cpu: "250m"
  limit:
    memory: "256Mi"
    cpu: "250m"
  user: postgres
  pass: postgres
  name: postgres
queue:
  replicaCount: 1
  limit:
    memory: "200Mi"
    cpu: "100m"
web:
  replicaCount: 1
  limit:
    memory: "512Mi"
    cpu: "500m"
worker:
  replicaCount: 1
  limit:
    memory: "512Mi"
    cpu: "500m"
