version: '3.4'
services:
  web:
    build: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  worker:
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432

  cache:
    image: redis:6-alpine
    ports:
    - 6379

  queue:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672"
      - "15672"