apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
spec:
  replicas: {{ .Values.cache.replicaCount }}
  selector:
    matchLabels:
      app: cache
  serviceName: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis
        resources:
          limits:
            memory: {{ .Values.cache.limit.memory }}
            cpu: {{ .Values.cache.limit.cpu }}


---

apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  type: ClusterIP
  ports:
  - name: cache
    port: 6379
  selector:
    app: cache
