apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.pass }}
        - name: POSTGRES_DB
          value: {{ .Values.db.db }}
        resources:
          requests:
            memory: {{ .Values.db.request.memory }}
            cpu: {{ .Values.db.request.cpu }}
          limits:
            memory: {{ .Values.db.limit.memory }}
            cpu: {{ .Values.db.limit.cpu }}
---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
  selector:
    app: db
