apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue
spec:
  replicas: {{ .Values.queue.replicaCount }}
  selector:
    matchLabels:
      app: queue
  serviceName: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: {{ .Values.queue.image }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.queue.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.queue.pass }}
        resources:
          limits:
            memory: {{ .Values.queue.limit.memory }}
            cpu: {{ .Values.queue.limit.cpu }}

---

apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  type: ClusterIP
  ports:
  - name: queue
    port: 5672
  - name: admin
    port: 15672
  selector:
    app: queue
