apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        command: ["./run_celery.sh"]
        resources:
          limits:
            memory: {{ .Values.worker.limit.memory }}
            cpu: {{ .Values.worker.limit.cpu }}
